# The name of the workflow
name: Go App

# This workflow is triggered on push and pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define a job named "build" that runs on an Ubuntu runner
jobs:
  build:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    # Steps are a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository to the runner
      - uses: actions/checkout@v4

      # Setup Go environment for the job
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      # Build the Go application
      - name: Build
        run: |
          go build -v ./...

      # Run the tests in the Go application
      - name: Run Tests
        run: go test -v ./...

      # Run golangci-lint on the Go code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      # Check for misspelled words in the code
      - uses: sobolevn/misspell-fixer-action@master

      # Run static analysis on the Go code
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

      # Lint the Dockerfile using Checkov
      - name: Lint Dockerfile using Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile
          quiet: true
          container_user: 1000
          check: "MEDIUM,HIGH,CRITICAL"
